# Metadata
site_name: Kolltool Docs
site_url: https://kolltooldocs.vfll.de
site_author: Ulrich Kilian 

# Repository
repo_name: scienceuli/vfllwiki
repo_url: https://github.com/scienceuli/vfllwiki

# Navigation
nav: 
  - Home: index.md
  - Profil: profiles.md
  - Teams: teams.md
  - Aufgaben: aufgaben.md
  - Dokumente und Verzeichnisse: documents.md
  - Nextcloud-Anbindung: nextcloud.md
  - Umfragen: polls.md
  - Meetings (BBB): bbb.md
  - Meetings (Zoom): zoom.md

# Material for MkDocs
theme:
  name: material
  custom_dir: docs/.overrides

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox
